events { worker_connections 1024; }

http {
    server {
        listen 80;
        
        # Acceso a la Web Turística (Principal)
        location / {
            proxy_pass http://visitor-web:80;
        }

        # Acceso al Sistema Operativo (Admin)
        location /admin {
            proxy_pass http://admin-os:3000;
        }

        # Acceso a la API Core
        location /api {
            proxy_pass http://core:8000;
        }
    }
}
